---
# Reload Daemon
- name: Reload Daemon
  systemd:  
    daemon_reload: yes

# Stop Services
- name: Stop GoApp
  service:  
    name: goapp 
    state: stopped

# Start Services
- name: Start GoApp
  service:  
    name: goapp 
    state: started 
    enabled: yes

# Restart Services
- name: Restart GoApp
  service:  
    name: goapp 
    state: restarted