---
# Stop Services
- name: Stop Nginx
  service:  
    name: nginx 
    state: stopped

# Start Services
- name: Start Nginx
  service:  
    name: nginx 
    state: started 
    enabled: yes

# Restart Services
- name: Restart Nginx
  service:  
    name: nginx 
    state: restarted