---
- name: Install Requisite Packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','git','apache2-utils','libnss3-tools']
    state: present
    update_cache: yes

- name: Add User to Existing Groups
  user:
    name: "{{ansible_user}}"
    shell: /bin/bash
    groups:
      - sudo    
    append: yes
    state: present
  notify: Reload Daemon