---
- name: Create GoApp System Group 
  group:
    name: goapp
    system: yes
    state: present

- name: Add GoApp User to Prometheus Group
  user:
    name: goapp
    shell: /sbin/nologin
    system: yes
    groups:
      - goapp  
    append: yes
    create_home: no
    state: present 

- name: Remove Existing Files in Folder
  file:
    path: "{{ansible_env.PWD}}/goprojects/src/"
    state: absent
    
- name: Deploy the Application
  git: 
    repo: 'https://github.com/samfil-technohub/samuel-nwoye-website.git'
    dest: "{{ansible_env.PWD}}/goprojects/src"
    mode: '0775'
    owner: goapp
    group: goapp
    #version: "{{ lookup('env','RELEASE_TAG') }}" #release-0.22

- name: Configure GoApp Service
  template:
    src: goapp.service.j2
    dest: /etc/systemd/system/goapp.service
    owner: goapp
    group: goapp
  notify:
    - Start GoApp

- name: Configure Nginx Proxy for the Application
  template:
    src: "{{item.src}}"
    dest: "/etc/nginx/conf.d/{{item.dest}}"
  loop:
    - {src: 'goapp.conf.j2', dest: 'nginx.conf'} 
  notify:
    - Reload Daemon 
    - Restart Nginx